version: '3.1'

services:
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "10080:8080"
    deploy:
      placement:
        constraints:
         - node.role==manager